Draft anchor support for script parameters.

diff --git a/_anchor b/_anchor
--- a/_anchor
+++ b/_anchor
@@ -1,5 +1,115 @@
 #!/usr/bin/env bash
 
+#Universal debugging filesystem.
+_user_log_anchor() {
+	# DANGER Do NOT create automatically, or reference any existing directory!
+	! [[ -d "$HOME"/.ubcore/userlog ]] && cat - > /dev/null 2>&1 && return 0
+	
+	#Terminal session may be used - the sessionid may be set through .bashrc/.ubcorerc .
+	if [[ "$sessionid" != "" ]]
+	then
+		cat - >> "$HOME"/.ubcore/userlog/a-"$sessionid".log
+		return 0
+	fi
+	cat - >> "$HOME"/.ubcore/userlog/a-undef.log
+	
+	return 0
+}
+
+#Cyan. Harmless status messages.
+_messagePlain_nominal() {
+	echo -e -n '\E[0;36m '
+	echo -n "$@"
+	echo -e -n ' \E[0m'
+	echo
+	return 0
+}
+
+#Blue. Diagnostic instrumentation.
+_messagePlain_probe() {
+	echo -e -n '\E[0;34m '
+	echo -n "$@"
+	echo -e -n ' \E[0m'
+	echo
+	return 0
+}
+
+#Blue. Diagnostic instrumentation.
+_messagePlain_probe_expr() {
+	echo -e -n '\E[0;34m '
+	echo -e -n "$@"
+	echo -e -n ' \E[0m'
+	echo
+	return 0
+}
+
+#Green. Working as expected.
+_messagePlain_good() {
+	echo -e -n '\E[0;32m '
+	echo -n "$@"
+	echo -e -n ' \E[0m'
+	echo
+	return 0
+}
+
+#Yellow. May or may not be a problem.
+_messagePlain_warn() {
+	echo -e -n '\E[1;33m '
+	echo -n "$@"
+	echo -e -n ' \E[0m'
+	echo
+	return 0
+}
+
+#Red. Will result in missing functionality, reduced performance, etc, but not necessarily program failure overall.
+_messagePlain_bad() {
+	echo -e -n '\E[0;31m '
+	echo -n "$@"
+	echo -e -n ' \E[0m'
+	echo
+	return 0
+}
+
+##Parameters
+#"--shell", ""
+#"--profile"
+#"--parent", "--embed", "--return", "--devenv"
+#"--call", "--script" "--bypass"
+
+ub_import=
+ub_import_param=
+ub_import_script=
+ub_loginshell=
+
+[[ "${BASH_SOURCE[0]}" != "${0}" ]] && ub_import="true"
+([[ "$1" == '--profile' ]] || [[ "$1" == '--script' ]] || [[ "$1" == '--call' ]] || [[ "$1" == '--return' ]] || [[ "$1" == '--devenv' ]] || [[ "$1" == '--shell' ]] || [[ "$1" == '--bypass' ]] || [[ "$1" == '--parent' ]] || [[ "$1" == '--embed' ]]) && ub_import_param="$1" && shift
+([[ "$0" == "/bin/bash" ]] || [[ "$0" == "-bash" ]] || [[ "$0" == "/usr/bin/bash" ]] || [[ "$0" == "bash" ]]) && ub_loginshell="true"	#Importing ubiquitous bash into a login shell with "~/.bashrc" is the only known cause for "_getScriptAbsoluteLocation" to return a result such as "/bin/bash".
+[[ "$ub_import" == "true" ]] && ! [[ "$ub_loginshell" == "true" ]] && ub_import_script="true"
+
+_messagePlain_probe_expr '$0= '"$0"'\n ''$1= '"$1"'\n ''ub_import= '"$ub_import"'\n ''ub_import_param= '"$ub_import_param"'\n ''ub_import_script= '"$ub_import_script"'\n ''ub_loginshell= '"$ub_loginshell" | _user_log_anchor
+
+# DANGER Prohibited import from login shell. Use _setupUbiquitous, call from another script, or manually set importScriptLocation.
+# WARNING Import from shell can be detected. Import from script cannot. Asserting that script has been imported is possible. Asserting that script has not been imported is not possible. Users may be protected from interactive mistakes. Script developers are NOT protected.
+if [[ "$ub_import_param" == "--profile" ]]
+then
+	([[ "$profileScriptLocation" == "" ]] ||  [[ "$profileScriptFolder" == "" ]]) && _messagePlain_bad 'import: profile: missing: profileScriptLocation, missing: profileScriptFolder' | _user_log_anchor && return 1
+elif ([[ "$ub_import_param" == "--parent" ]] || [[ "$ub_import_param" == "--embed" ]] || [[ "$ub_import_param" == "--return" ]] || [[ "$ub_import_param" == "--devenv" ]])
+then
+	([[ "$scriptAbsoluteLocation" == "" ]] || [[ "$scriptAbsoluteFolder" == "" ]] || [[ "$sessionid" == "" ]]) && _messagePlain_bad 'import: parent: missing: scriptAbsoluteLocation, missing: scriptAbsoluteFolder, missing: sessionid' | _user_log_anchor && return 1
+elif [[ "$ub_import_param" == "--call" ]] || [[ "$ub_import_param" == "--script" ]] || [[ "$ub_import_param" == "--bypass" ]] || [[ "$ub_import_param" == "--shell" ]] || ([[ "$ub_import" == "true" ]] && [[ "$ub_import_param" == "" ]])
+then
+	([[ "$importScriptLocation" == "" ]] ||  [[ "$importScriptFolder" == "" ]]) && _messagePlain_bad 'import: call: missing: importScriptLocation, missing: importScriptFolder' | _user_log_anchor && return 1
+elif [[ "$ub_import" != "true" ]]	#"--shell", ""
+then
+	_messagePlain_warn 'import: undetected: cannot determine if imported' | _user_log_anchor
+	true #no problem
+else	#FAIL, implies [[ "$ub_import" == "true" ]]
+	_messagePlain_bad 'import: fall: fail' | _user_log_anchor && return 1
+	exit 1
+fi
+
+[[ "$ub_import" != "true" ]] && ub_import_param=
+
 #Critical prerequsites.
 _getAbsolute_criticalDep() {
 	! type realpath > /dev/null 2>&1 && return 1
@@ -114,67 +224,6 @@ _uid() {
 	cat /dev/urandom 2> /dev/null | base64 2> /dev/null | tr -dc 'a-zA-Z0-9' 2> /dev/null | head -c "$uidLength" 2> /dev/null
 }
 
-#Universal debugging filesystem.
-_user_log_anchor() {
-	# DANGER Do NOT create automatically, or reference any existing directory!
-	! [[ -d "$HOME"/.ubcore/userlog ]] && cat - > /dev/null 2>&1 && return 0
-	
-	#Terminal session may be used - the sessionid may be set through .bashrc/.ubcorerc .
-	if [[ "$sessionid" != "" ]]
-	then
-		cat - >> "$HOME"/.ubcore/userlog/a-"$sessionid".log
-		return 0
-	fi
-	cat - >> "$HOME"/.ubcore/userlog/a-undef.log
-	
-	return 0
-}
-
-#Cyan. Harmless status messages.
-_messagePlain_nominal() {
-	echo -e -n '\E[0;36m '
-	echo -n "$@"
-	echo -e -n ' \E[0m'
-	echo
-	return 0
-}
-
-#Blue. Diagnostic instrumentation.
-_messagePlain_probe() {
-	echo -e -n '\E[0;34m '
-	echo -n "$@"
-	echo -e -n ' \E[0m'
-	echo
-	return 0
-}
-
-#Green. Working as expected.
-_messagePlain_good() {
-	echo -e -n '\E[0;32m '
-	echo -n "$@"
-	echo -e -n ' \E[0m'
-	echo
-	return 0
-}
-
-#Yellow. May or may not be a problem.
-_messagePlain_warn() {
-	echo -e -n '\E[1;33m '
-	echo -n "$@"
-	echo -e -n ' \E[0m'
-	echo
-	return 0
-}
-
-#Red. Will result in missing functionality, reduced performance, etc, but not necessarily program failure overall.
-_messagePlain_bad() {
-	echo -e -n '\E[0;31m '
-	echo -n "$@"
-	echo -e -n ' \E[0m'
-	echo
-	return 0
-}
-
 #Demarcate major steps.
 _messageNormal() {
 	echo -e -n '\E[1;32;46m '
@@ -262,8 +311,12 @@ _launch_anchor() {
 	recursionExec="$anchorScriptAbsoluteFolder"/../"$anchorSourcePath"
 	if _recursion_guard "$recursionExec"
 	then
-		_messagePlain_good 'self: '"$recursionExec"  "$anchorName" "$@" | _user_log_anchor
-		"$recursionExec" "$anchorName" "$@"
+		[[ "$ub_import" != "true" ]] && _messagePlain_good 'self: '"$recursionExec" "$anchorName" "$@" | _user_log_anchor
+			[[ "$ub_import" != "true" ]] && "$recursionExec" "$anchorName" "$@"
+		
+		[[ "$ub_import" == "true" ]] && _messagePlain_good 'self: '"$recursionExec" "$ub_import_param" "$anchorName" "$@" | _user_log_anchor
+			[[ "$ub_import" == "true" ]] && "$recursionExec" "$ub_import_param" "$anchorName" "$@"
+		
 		exit $?
 	fi
 	
@@ -272,12 +325,14 @@ _launch_anchor() {
 	then
 		if [[ "$anchorDestination" == *"ubiquitous_bash.sh" ]]
 		then
-			_messagePlain_good 'launch: '"$anchorDestination" "$anchorName" "$@" | _user_log_anchor
-			"$anchorDestination" "$anchorName" "$@"
+			_messagePlain_good 'launch: '"$anchorDestination" "$ub_import_param" "$anchorName" "$@" | _user_log_anchor
+			[[ "$ub_import" != "true" ]] && "$anchorDestination" "$anchorName" "$@"
+			[[ "$ub_import" == "true" ]] && "$anchorDestination" "$ub_import_param" "$anchorName" "$@"
 			exit $?
 		fi
-		_messagePlain_good 'launch: '"$anchorDestination" "$@" | _user_log_anchor
-		"$anchorDestination" "$@"
+		_messagePlain_good 'launch: '"$anchorDestination" "$ub_import_param" "$@" | _user_log_anchor
+		[[ "$ub_import" != "true" ]] && "$anchorDestination" "$@"
+		[[ "$ub_import" == "true" ]] && "$anchorDestination" "$ub_import_param" "$@"
 		exit $?
 	fi
 	
@@ -290,8 +345,9 @@ _launch_anchor() {
 		if [[ "$anchorDestination" != "" ]]
 		then
 			_messagePlain_probe 'anchorDestination='"$anchorDestination" | _user_log_anchor
-			_messagePlain_good 'launch: '"$anchorDestination" "$@" | _user_log_anchor
-			"$anchorDestination" "$@"
+			_messagePlain_good 'launch: '"$anchorDestination" "$ub_import_param" "$@" | _user_log_anchor
+			[[ "$ub_import" != "true" ]] && "$anchorDestination" "$@"
+			[[ "$ub_import" == "true" ]] && "$anchorDestination" "$ub_import_param" "$anchorName" "$@"
 			exit $?
 		fi
 	fi
@@ -299,64 +355,88 @@ _launch_anchor() {
 	recursionExec="$HOME"/core/infrastructure/vm/"$anchorSourcePath"
 	if _recursion_guard "$recursionExec"
 	then
-		_messagePlain_good 'launch: '"$recursionExec" "$@" | _user_log_anchor
-		"$recursionExec" "$anchorName" "$@"
+		[[ "$ub_import" != "true" ]] && _messagePlain_good 'launch: '"$recursionExec" "$anchorName" "$@" | _user_log_anchor
+			[[ "$ub_import" != "true" ]] && "$recursionExec" "$anchorName" "$@"
+		
+		[[ "$ub_import" == "true" ]] && _messagePlain_good 'launch: '"$recursionExec" "$ub_import_param" "$anchorName" "$@" | _user_log_anchor
+			[[ "$ub_import" == "true" ]] && "$recursionExec" "$ub_import_param" "$anchorName" "$@"
 		exit $?
 	fi
 
 	recursionExec="$HOME"/core/extra/infrastructure/vm/"$anchorSourcePath"
 	if _recursion_guard "$recursionExec"
 	then
-		_messagePlain_good 'launch: '"$recursionExec" "$@" | _user_log_anchor
-		"$recursionExec" "$anchorName" "$@"
+		[[ "$ub_import" != "true" ]] && _messagePlain_good 'launch: '"$recursionExec" "$anchorName" "$@" | _user_log_anchor
+			[[ "$ub_import" != "true" ]] && "$recursionExec" "$anchorName" "$@"
+		
+		[[ "$ub_import" == "true" ]] && _messagePlain_good 'launch: '"$recursionExec" "$ub_import_param" "$anchorName" "$@" | _user_log_anchor
+			[[ "$ub_import" == "true" ]] && "$recursionExec" "$ub_import_param" "$anchorName" "$@"
 		exit $?
 	fi
 	
 	recursionExec="$HOME"/core/installations/"$anchorSourcePath"
 	if _recursion_guard "$recursionExec"
 	then
-		_messagePlain_good 'launch: '"$recursionExec" "$@" | _user_log_anchor
-		"$recursionExec" "$anchorName" "$@"
+		[[ "$ub_import" != "true" ]] && _messagePlain_good 'launch: '"$recursionExec" "$anchorName" "$@" | _user_log_anchor
+			[[ "$ub_import" != "true" ]] && "$recursionExec" "$anchorName" "$@"
+		
+		[[ "$ub_import" == "true" ]] && _messagePlain_good 'launch: '"$recursionExec" "$ub_import_param" "$anchorName" "$@" | _user_log_anchor
+			[[ "$ub_import" == "true" ]] && "$recursionExec" "$ub_import_param" "$anchorName" "$@"
 		exit $?
 	fi
 
 	recursionExec="$HOME"/core/extra/installations/"$anchorSourcePath"
 	if _recursion_guard "$recursionExec"
 	then
-		_messagePlain_good 'launch: '"$recursionExec" "$@" | _user_log_anchor
-		"$recursionExec" "$anchorName" "$@"
+		[[ "$ub_import" != "true" ]] && _messagePlain_good 'launch: '"$recursionExec" "$anchorName" "$@" | _user_log_anchor
+			[[ "$ub_import" != "true" ]] && "$recursionExec" "$anchorName" "$@"
+		
+		[[ "$ub_import" == "true" ]] && _messagePlain_good 'launch: '"$recursionExec" "$ub_import_param" "$anchorName" "$@" | _user_log_anchor
+			[[ "$ub_import" == "true" ]] && "$recursionExec" "$ub_import_param" "$anchorName" "$@"
 		exit $?
 	fi
 
 	recursionExec="$HOME"/core/lab/"$anchorEntity""$anchorLabName"/_index/"$anchorName"
 	if _recursion_guard "$recursionExec"
 	then
-		_messagePlain_good 'launch: '"$recursionExec" "$@" | _user_log_anchor
-		"$recursionExec" "$@"
+		[[ "$ub_import" != "true" ]] && _messagePlain_good 'reference: '"$recursionExec" "$@" | _user_log_anchor
+			[[ "$ub_import" != "true" ]] && "$recursionExec" "$@"
+		
+		[[ "$ub_import" == "true" ]] && _messagePlain_good 'reference: '"$recursionExec" "$ub_import_param" "$@" | _user_log_anchor
+			[[ "$ub_import" == "true" ]] && "$recursionExec" "$ub_import_param" "$@"
 		exit $?
 	fi
 
 	recursionExec="$HOME"/core/extra/lab/"$anchorEntity""$anchorLabName"/_index/"$anchorName"
 	if _recursion_guard "$recursionExec"
 	then
-		_messagePlain_good 'launch: '"$recursionExec" "$@" | _user_log_anchor
-		"$recursionExec" "$@"
+		[[ "$ub_import" != "true" ]] && _messagePlain_good 'reference: '"$recursionExec" "$@" | _user_log_anchor
+			[[ "$ub_import" != "true" ]] && "$recursionExec" "$@"
+		
+		[[ "$ub_import" == "true" ]] && _messagePlain_good 'reference: '"$recursionExec" "$ub_import_param" "$@" | _user_log_anchor
+			[[ "$ub_import" == "true" ]] && "$recursionExec" "$ub_import_param" "$@"
 		exit $?
 	fi
 
 	recursionExec="$HOME"/core/lab/"$anchorEntity""$anchorLabNameAlt"/_index/"$anchorName"
 	if _recursion_guard "$recursionExec"
 	then
-		_messagePlain_good 'launch: '"$recursionExec" "$@" | _user_log_anchor
-		"$recursionExec" "$@"
+		[[ "$ub_import" != "true" ]] && _messagePlain_good 'reference: '"$recursionExec" "$@" | _user_log_anchor
+			[[ "$ub_import" != "true" ]] && "$recursionExec" "$@"
+		
+		[[ "$ub_import" == "true" ]] && _messagePlain_good 'reference: '"$recursionExec" "$ub_import_param" "$@" | _user_log_anchor
+			[[ "$ub_import" == "true" ]] && "$recursionExec" "$ub_import_param" "$@"
 		exit $?
 	fi
 
 	recursionExec="$HOME"/core/extra/lab/"$anchorEntity""$anchorLabNameAlt"/_index/"$anchorName"
 	if _recursion_guard "$recursionExec"
 	then
-		_messagePlain_good 'launch: '"$recursionExec" "$@" | _user_log_anchor
-		"$recursionExec" "$@"
+		[[ "$ub_import" != "true" ]] && _messagePlain_good 'reference: '"$recursionExec" "$@" | _user_log_anchor
+			[[ "$ub_import" != "true" ]] && "$recursionExec" "$@"
+		
+		[[ "$ub_import" == "true" ]] && _messagePlain_good 'reference: '"$recursionExec" "$ub_import_param" "$@" | _user_log_anchor
+			[[ "$ub_import" == "true" ]] && "$recursionExec" "$ub_import_param" "$@"
 		exit $?
 	fi
 	_messagePlain_bad 'missing: '"$anchorSource" | _user_log_anchor
